name: ARCHIVED Hello World

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello World"
