name: TEST 3 - Hello World

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: CHECK PWD
        run: pwd
      - name: CHECK FILES
        run: find . -type f -print
      - name: SCRIPT TEST
        shell: bash
        run: ./.github/scripts/test.sh
      - name: Save file access times BEFORE run
        run: bash ./get-access-times-before.sh
      - name: Say hello
        run: echo "Hello World" > OUTPUT/output.txt
      - name: Save file access times AFTER run
        run: bash ./get-access-times-after.sh
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: OUTPUT FOLDER
          path: OUTPUTS/
 
