name: TEST 3 - Hello World

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello World" > output.txt
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: output.txt
          path: output.txt
